### PR TITLE
Test authchanges

### PR DESCRIPTION
**Pull request by tiger5226**

### CODE REVIEW

**Comment by aarondl** [comment]
Wow. Although it seems to have been in error that this pull request was opened. It's a pretty interesting one. Several fixes that I don't think we have, and even some extra features. I wonder why the author never tried to pull request any of them.

**Comment by tiger5226** [comment]
Sorry that is our local fork. And I was trying to fix the issue because it was urgent. We are happy to share these updates I am sure.

**Comment by lyoshenka** [comment]
I have filed a few PRs, but it takes time and I've been pretty busy. I could certainly do more. As for new features, some of them are actually not very good (e.g. the Filter stuff is a mistake. using qm is more flexible, but I didn't understand it at first), some make assumptions about the structure of the db (e.g. that there's always an id column), and others only target mysql, since that's all we use, so I don't test other dbs.

**Comment by lyoshenka** [comment]
I'm happy you think its interesting though :smile:

**Pull request closed without merging**
