### PR TITLE
Some code improvements

### PR DESCRIPTION
**Pull request by sosiska**
* strings.ReplaceAll instead of strings.Replace with -1.
* Change strings.ToLower comparison to strings.EqualFold.
* Simplify some functions.
* Rewrite switch statements with only one case as if.
* Some assignments simplified by using assignment operators.
* Put missing space between `//` and comment text.

### CODE REVIEW

**Comment by aarondl** [comment]
Thanks for this. Was this done mechanically or manually?

Also despite using Go since v1 I had no idea EqualFold existed, has that existed since the beginning as I couldn't find it in the release notes anywhere.

**Comment by sosiska** [comment]
@aarondl it was linter go-critic

**Comment by lucaslsl** [comment]
@aarondl `strings.ReplaceAll` was added on `Go 1.12` if i'm not mistaken, so this breaks anything below that. I figured the hard way by naively not locking the cli and having my CI builds fail.

**Comment by aarondl** [comment]
Thanks for the heads up. This is fine by me. Supporting 1 major version behind is what I strive for. Sorry to hear you got broken!

Any particular reason you're still using an older Go?

**Comment by lucaslsl** [comment]
No really, in fact I just upgraded to `1.13`. It's a project that hadnt be touched in a while.

**Comment by touyu** [comment]
I'm using GAE/SE go1.11.
GAE/SE becomes 2nd Gen from go1.12,  and there is a big destructive change, so it is difficult to raise Go version for me.
I want you to consider supporting go1.11.

**Comment by touyu** [comment]
@aarondl
I'm using GAE/SE go1.11.
GAE/SE becomes 2nd Gen from go1.12, and there is a big destructive change, so it is difficult to raise Go version for me.
I want you to consider supporting go1.11.

**Comment by aarondl** [comment]
I apologize touyu but I have no interest in maintaining older versions. Go 1.11 is over a year old now. Just like your Go version is pinned to something older you can take the same approach for sqlboiler, we tag all of our releases so it should be easy to use it at an older version.

**Pull request merged**
