### PR TITLE
Add Expression query mod

### PR DESCRIPTION
**Pull request by varyoo**
Allow to query custom columns with arguments like this:

```Go
models.Articles(qm.Expression("MATCH (title) AGAINST (?) AS score", "+MySQL")).
  Bind(ctx, db, &fullTextSearchResults)
```

:blush:

### CODE REVIEW

**Comment by aarondl** [comment]
Is this shared with any other database engine? Or is it just mysql?

**Comment by varyoo** [comment]
`MATCH AGAINST` is purely MySQL, why?

**Comment by vhakulinen** [comment]
Related: postgresql has syntax for doing a distinct select on a column (e.g. `SELECT DISTINCT ON (col1) col1, col2 ...`): https://www.postgresql.org/docs/12/sql-select.html#SQL-DISTINCT. If the placement of `Expression` query mod would be dependent on the order it was defined in the `NewQuery` args, this could also allow psql's `DISTINCT ON`.

E.g.
```go
models.Aricles(qm.Expression("DISTINCT ON (foo)"), qm.Select("foo", "bar"))
```
would become
```sql
SELECT DISTINCT ON (foo), foo, bar FROM articles```

**Comment by aarondl** [comment]
@varyoo I typically like to refrain from adding highly specific query mods (especially database specific).

@vhakulinen the query mod ordering isn't tracked anywhere unfortunately :(

**Comment by aarondl** [comment]
One thing to note is I'm very much considering opening up the query struct so that we can have custom query mods in the wild. I think that would be very nice.

**Pull request closed without merging**
