### PR TITLE
Add missing func (...Query) UpdateAllGP(...) to the update template.

### PR DESCRIPTION
**Pull request by MeanSquaredError**
This is a fix for #1062. Tested and seems to work for me.

### CODE REVIEW

**Comment by stephenafamo** [comment]
Can you change the merge target to `dev`?

**Comment by MeanSquaredError** [comment]
OK, one moment. Let me see how to do that properly.

**Comment by MeanSquaredError** [comment]
OK, I think it is against the dev branch now.

**Comment by stephenafamo** [comment]
Merged to dev. It will be included in the next release

**Pull request merged**
