### PR TITLE
ignore FK if FK table not in whitelist or in blacklist

### PR DESCRIPTION
**Pull request by ceshihao**
A PR for #185 
Ignore FK relationship if FK table is not in whitelist or blacklist.

### CODE REVIEW

**Comment by aarondl** [comment]
Nice. This is a good feature to have. But I can't help but notice there's a lot of repetition at the driver level. I wonder if this functionality couldn't be created as a filter that runs around here: https://github.com/vattle/sqlboiler/blob/master/bdb/interface.go#L72

This absolves the drivers of the responsibility, creates fewer arguments to the functions downstream, and should also be able to provide the same functionality. What do you think?

**Comment by ceshihao** [comment]
Perhaps it can be added in func setForeignKeyConstraints.

https://github.com/volatiletech/sqlboiler/blob/master/bdb/interface.go#L118

**Comment by aarondl** [comment]
I'd say it should just be a new function, easier to test that way. It should take the foreign keys that exist + the list of tables, and cull foreign keys that don't belong to a table that exists in the list. I think this will work, yes?

**Comment by ceshihao** [comment]
move it to func filterForeignKeys

**Comment by aarondl** [comment]
Merged into `dev` branch: 9be8f90. This is our staging ground for "bigger" releases and is how you should submit PRs against dev branch usually (see [CONTRIBUTING.md](https://github.com/volatiletech/sqlboiler/blob/master/CONTRIBUTING.md)). Please help test it out :)

Thanks so much for your contributions!

**Comment by ceshihao** [comment]
OK, i will submit new PR to dev branch.

Sorry for inconvenience.

**Comment by saulortega** [comment]
This feature is not yet in version 2.6?

**Pull request closed without merging**
