### PR TITLE
feature: add mysql unix socket support

### LINKED ISSUE #425: mysql: using a unix domain socket
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v3.1.0

How do I use a unix domain socket. For example the a DSN with the Go mysql driver might be:

`root@unix(/var/run/mysqld/mysqld.sock)/public`

### PR DESCRIPTION
**Pull request by c9s**
Fixes #425 

When unix-socket is set, avoid using host+port

### CODE REVIEW

**Comment by c9s** [comment]
@aarondl please take a look, thanks

cc @philips

**Comment by philips** [comment]
I think I was ccd by mistake

**Comment by c9s** [comment]
> I think I was ccd by mistake

@philips nope, you opened this issue in 2018 :-D

**Comment by philips** [comment]
@c9s LOL! Well thank you!

**Pull request merged**
