### PR TITLE
README: fix MSSQL link text

### PR DESCRIPTION
**Pull request by philips**

### CODE REVIEW

**Comment by aarondl** [comment]
Thanks for the PR! Merged to dev (usually make your PRs against that branch).

**Comment by aarondl** [comment]
e1d6ad4

**Comment by philips** [comment]
There is a feature on GitHub to make a branch other than master the
default. Turning that on might be helpful.

**Comment by aarondl** [comment]
That feature also affects the branch that people get when they git clone (or go get) so it's not ideal.

**Pull request closed without merging**
