### PR TITLE
Update randomize.go

### PR DESCRIPTION
**Pull request by brianvoe**
Doesnt return an error anymore

### CODE REVIEW

**Comment by glerchundi** [comment]
This change rollbacks sqlboiler to an older version of satori/uuid so it is
not eligible to be merged.

**Comment by brianvoe** [comment]
I would suggest add dep to ensure things are using certain versions of dependencies cause right now i get build errors.

**Comment by saulortega** [comment]
Just update your library satori/uuid.

**Comment by aarondl** [comment]
As @saulortega mentioned, this is not eligible to be merged. The current version of satori/uuid has the error parameter, and if we merged this many users of sqlboiler will no longer be able to build. This is also a breaking change so something I can't make lightly. I think the best path is to update your version of uuid.

sqlboiler won't commit to dep because it doesn't look like the community has, probably looking at vgo when that comes out.

**Comment by CameronAckermanSEL** [comment]
@saulortega fyi https://github.com/satori/go.uuid/issues/73

**Pull request closed without merging**
