### PR TITLE
add missing DeleteAllG for query

### PR DESCRIPTION
**Pull request by Atrox**
adds the missing method `DeleteAllG` on the query.

### CODE REVIEW

**Comment by aarondl** [comment]
Will merge this soon. Thanks for the PR! Shows how few people use either `DeleteAll` or `G` variants that this has been missing for literally years lol.

**Comment by Atrox** [comment]
I just needed this for a specific use case. I never noticed it missing while using it in other projects. Funnily enough I thought something on my end was wrong when the method was missing. :D

Just want to say thank you for SQLBoiler. Such an amazing library to interact with the database in Go. I never looked back once I stumbled upon this.

Note: looks like I ran `bindata` on windows and now all the file sizes are different. If you want, I can rerun it on my Macbook.

**Comment by aarondl** [comment]
@Atrox Your very welcome! I re-ran bindata anyway. Sort of a substantial change as the mood bit me and we ended up moving to Go modules. Hopefully that's not a hindrance to you.

**Comment by Atrox** [comment]
Works great, thank you. Just upgraded a smaller project. :)

**Pull request merged**
