### PR TITLE
templates: add constants for eager loading relationships

### LINKED ISSUE #358: Export XXX in LoadXXX methods in order to avoid hardcoding
SQLBoiler: v3

I would like to avoid hardcoding eager loading references and it would be interesting if SQLBoiler could automagically include those names as constants in generated code.

It's related to [this issue](https://github.com/volatiletech/sqlboiler/issues/141) but this applies to the names used to make a references to relationships.

Nested relations (more than 1 depth ones) can be created by the developer if the first levels ones are included.

WDYT?

### PR DESCRIPTION
**Pull request by glerchundi**
Closes #358

Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

### CODE REVIEW

**Comment by glerchundi** [comment]
PTAL @aarondl, I applied the second approach all-in-one struct one.

**Comment by glerchundi** [comment]
> This is pretty verbose. I think we should possibly rename the Relationhips part in the templates to Rels or some other shorthand to make it just a bit more compact.

Done.

> This could go in strmangle or in qm. I leave it to you to make the decision. It's not truly a query mod, but it does help with query mods. The line is pretty blurry :)

I don't care so I will put it on `qm` package just because it'll be already imported. 

> There is also no accompanying documentation in the README for the change.

Done.

**Comment by glerchundi** [comment]
PTAL @aarondl

**Comment by glerchundi** [comment]
Upgraded `go-bindata` locally to v3.11.0 of Kevin Burke's fork and regenerate templates.

**Comment by aarondl** [comment]
Missed the go-bindata update, but I took care of it anyway. This is merged in master and v3 is released as of now. :)

**Comment by glerchundi** [comment]
👏🏻👏🏻👏🏻

**Pull request closed without merging**
