### PR TITLE
Use alias to determine whether to add a prefix to the relation name of the foreign key.

### PR DESCRIPTION
**Pull request by sadayuki-matsuno**
When alias is set to the table name, the same prefix is ​​added to the relation name of that table, so it was fixed.

For example, if you set the following alias to the table cves, the name of Rels in that table was SomeCveXxxx.

```
[[aliases.tables]]
  name          = "some_cves"
  up_plural     = "SomeCves"
  up_singular   = "SomeCve"
  down_plural   = "someCves"
  down_singular = "someCve"
```

I added a new name_singular in the definition of this alias and created a rel field using that value.

```
[[aliases.tables]]
  name          = "some_cves"
  name_singular = "some_cve"
  up_plural     = "SomeCves"
  up_singular   = "SomeCve"
  down_plural   = "someCves"
  down_singular = "someCve"
```

### CODE REVIEW

**Comment by aarondl** [comment]
> When alias is set to the table name, the same prefix is ​​added to the relation name of that table, so it was fixed.

I'm trying to understand what this means. Perhaps this relates to: https://github.com/volatiletech/sqlboiler/issues/576 ?

**Comment by sadayuki-matsuno** [comment]
Similar to #576, but slightly different.
What I want to solve is not the conflict, but the name of the relation function. (I don't know if that would be conflict resolution or not.

For tables with alias set, the function name of the relation is not based on the name of the alias, so it is a redundant function name.

For example. if we have a table and a alias config like the following.

```
CREATE TABLE cves (
        id BIGSERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE children(
        id BIGSERIAL PRIMARY KEY NOT NULL,
        cve_id bigint NOT NULL REFERENCES cves(id),
        aa text,
        created_at timestamp without time zone DEFAULT statement_timestamp() NOT NULL,
        updated_at timestamp without time zone DEFAULT statement_timestamp() NOT NULL
);
```

```
[[aliases.tables]]
  name          = "cves"
  up_plural     = "Cves"
  up_singular   = "Cve"
  down_plural   = "Cves"
  down_singular = "Cve"
```

In this case, the relation definition of children created for cve is as follows

```
var CveRels = struct {
    CveChildren string
}{
    CveChildren: "CveChildren",
}
```

I assume that this is a prefix addition caused by sqlboiler mistaking the singular of `cve` for `cfe`.
Therefore, my intention is to avoid such useless prefixes by setting the sqlboiler to the singular I intend.

If I run it with my PR, the above relation definition should look like this.

```
var CveRels = struct {
    Children string
}{
    Children: "Children",
}
```

**Comment by aarondl** [comment]
How does this continue to work with qm.Load() as I see no changes made to the names of the eager loading functions that are generated?

**Comment by sadayuki-matsuno** [comment]
In my local, the name of the function used in Load appears to have changed as well.
And EagerLoad is working fine.

The following is the difference.

```
diff --git a/backend/pkg/dbmodels/boil_suites_test.go b/backend/pkg/dbmodels/boil_suites_test.go
index 67d5b92..44aab63 100644
--- a/backend/pkg/dbmodels/boil_suites_test.go
+++ b/backend/pkg/dbmodels/boil_suites_test.go
@@ -81,13 +81,13 @@ func TestOneToOne(t *testing.T) {}
 // TestToMany tests cannot be run in parallel
 // or deadlocks can occur.
 func TestToMany(t *testing.T) {
-	t.Run("CveToCveChildren", testCveToManyCveChildren)
+	t.Run("CveToChildren", testCveToManyChildren)
 }
 
 // TestToOneSet tests cannot be run in parallel
 // or deadlocks can occur.
 func TestToOneSet(t *testing.T) {
-	t.Run("ChildToCveUsingCveChildren", testChildToOneSetOpCveUsingCve)
+	t.Run("ChildToCveUsingChildren", testChildToOneSetOpCveUsingCve)
 }
 
 // TestToOneRemove tests cannot be run in parallel
@@ -105,7 +105,7 @@ func TestOneToOneRemove(t *testing.T) {}
 // TestToManyAdd tests cannot be run in parallel
 // or deadlocks can occur.
 func TestToManyAdd(t *testing.T) {
-	t.Run("CveToCveChildren", testCveToManyAddOpCveChildren)
+	t.Run("CveToChildren", testCveToManyAddOpChildren)
 }
 
 // TestToManySet tests cannot be run in parallel
diff --git a/backend/pkg/dbmodels/children.go b/backend/pkg/dbmodels/children.go
index 3c0b0d7..91e4bac 100644
--- a/backend/pkg/dbmodels/children.go
+++ b/backend/pkg/dbmodels/children.go
@@ -339,7 +339,7 @@ func (childL) LoadCve(ctx context.Context, e boil.ContextExecutor, singular bool
 		if foreign.R == nil {
 			foreign.R = &CveR{}
 		}
-		foreign.R.CveChildren = append(foreign.R.CveChildren, object)
+		foreign.R.Children = append(foreign.R.Children, object)
 		return nil
 	}
 
@@ -350,7 +350,7 @@ func (childL) LoadCve(ctx context.Context, e boil.ContextExecutor, singular bool
 				if foreign.R == nil {
 					foreign.R = &CveR{}
 				}
-				foreign.R.CveChildren = append(foreign.R.CveChildren, local)
+				foreign.R.Children = append(foreign.R.Children, local)
 				break
 			}
 		}
@@ -361,7 +361,7 @@ func (childL) LoadCve(ctx context.Context, e boil.ContextExecutor, singular bool
 
 // SetCve of the child to the related item.
 // Sets o.R.Cve to related.
-// Adds o to related.R.CveChildren.
+// Adds o to related.R.Children.
 func (o *Child) SetCve(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Cve) error {
 	var err error
 	if insert {
@@ -397,10 +397,10 @@ func (o *Child) SetCve(ctx context.Context, exec boil.ContextExecutor, insert bo
 
 	if related.R == nil {
 		related.R = &CveR{
-			CveChildren: ChildSlice{o},
+			Children: ChildSlice{o},
 		}
 	} else {
-		related.R.CveChildren = append(related.R.CveChildren, o)
+		related.R.Children = append(related.R.Children, o)
 	}
 
 	return nil
diff --git a/backend/pkg/dbmodels/children_test.go b/backend/pkg/dbmodels/children_test.go
index c7688ba..5f43e22 100644
--- a/backend/pkg/dbmodels/children_test.go
+++ b/backend/pkg/dbmodels/children_test.go
@@ -442,7 +442,7 @@ func testChildToOneSetOpCveUsingCve(t *testing.T) {
 			t.Error("relationship struct not set to correct value")
 		}
 
-		if x.R.CveChildren[0] != &a {
+		if x.R.Children[0] != &a {
 			t.Error("failed to append to foreign relationship struct")
 		}
 		if a.CveID != x.ID {
diff --git a/backend/pkg/dbmodels/cves.go b/backend/pkg/dbmodels/cves.go
index b1359f3..f9d1091 100644
--- a/backend/pkg/dbmodels/cves.go
+++ b/backend/pkg/dbmodels/cves.go
@@ -45,14 +45,14 @@ var CveWhere = struct {
 
 // CveRels is where relationship names are stored.
 var CveRels = struct {
-	CveChildren string
+	Children string
 }{
-	CveChildren: "CveChildren",
+	Children: "Children",
 }
 
 // CveR is where relationships are stored.
 type CveR struct {
-	CveChildren ChildSlice `boil:"CveChildren" json:"CveChildren" toml:"CveChildren" yaml:"CveChildren"`
+	Children ChildSlice `boil:"Children" json:"Children" toml:"Children" yaml:"Children"`
 }
 
 // NewStruct creates a new relationship struct
@@ -161,8 +161,8 @@ func (q CveQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool,
 	return count > 0, nil
 }
 
-// CveChildren retrieves all the child's Children with an executor via cve_id column.
-func (o *Cve) CveChildren(mods ...qm.QueryMod) childQuery {
+// Children retrieves all the child's Children with an executor.
+func (o *Cve) Children(mods ...qm.QueryMod) childQuery {
 	var queryMods []qm.QueryMod
 	if len(mods) != 0 {
 		queryMods = append(queryMods, mods...)
@@ -182,9 +182,9 @@ func (o *Cve) CveChildren(mods ...qm.QueryMod) childQuery {
 	return query
 }
 
-// LoadCveChildren allows an eager lookup of values, cached into the
+// LoadChildren allows an eager lookup of values, cached into the
 // loaded structs of the objects. This is for a 1-M or N-M relationship.
-func (CveL) LoadCveChildren(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCve interface{}, mods queries.Applicator) error {
+func (CveL) LoadChildren(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCve interface{}, mods queries.Applicator) error {
 	var slice []*Cve
 	var object *Cve
 
@@ -247,7 +247,7 @@ func (CveL) LoadCveChildren(ctx context.Context, e boil.ContextExecutor, singula
 	}
 
 	if singular {
-		object.R.CveChildren = resultSlice
+		object.R.Children = resultSlice
 		for _, foreign := range resultSlice {
 			if foreign.R == nil {
 				foreign.R = &childR{}
@@ -260,7 +260,7 @@ func (CveL) LoadCveChildren(ctx context.Context, e boil.ContextExecutor, singula
 	for _, foreign := range resultSlice {
 		for _, local := range slice {
 			if local.ID == foreign.CveID {
-				local.R.CveChildren = append(local.R.CveChildren, foreign)
+				local.R.Children = append(local.R.Children, foreign)
 				if foreign.R == nil {
 					foreign.R = &childR{}
 				}
@@ -273,11 +273,11 @@ func (CveL) LoadCveChildren(ctx context.Context, e boil.ContextExecutor, singula
 	return nil
 }
 
-// AddCveChildren adds the given related objects to the existing relationships
+// AddChildren adds the given related objects to the existing relationships
 // of the cfe, optionally inserting them as new records.
-// Appends related to o.R.CveChildren.
+// Appends related to o.R.Children.
 // Sets related.R.Cve appropriately.
-func (o *Cve) AddCveChildren(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Child) error {
+func (o *Cve) AddChildren(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Child) error {
 	var err error
 	for _, rel := range related {
 		if insert {
@@ -308,10 +308,10 @@ func (o *Cve) AddCveChildren(ctx context.Context, exec boil.ContextExecutor, ins
 
 	if o.R == nil {
 		o.R = &CveR{
-			CveChildren: related,
+			Children: related,
 		}
 	} else {
-		o.R.CveChildren = append(o.R.CveChildren, related...)
+		o.R.Children = append(o.R.Children, related...)
 	}
 
 	for _, rel := range related {
diff --git a/backend/pkg/dbmodels/cves_test.go b/backend/pkg/dbmodels/cves_test.go
index 47c7b3a..2acbedc 100644
--- a/backend/pkg/dbmodels/cves_test.go
+++ b/backend/pkg/dbmodels/cves_test.go
@@ -353,7 +353,7 @@ func testCvesInsertWhitelist(t *testing.T) {
 	}
 }
 
-func testCveToManyCveChildren(t *testing.T) {
+func testCveToManyChildren(t *testing.T) {
 	var err error
 	ctx := context.Background()
 	tx := MustTx(boil.BeginTx(ctx, nil))
@@ -388,7 +388,7 @@ func testCveToManyCveChildren(t *testing.T) {
 		t.Fatal(err)
 	}
 
-	check, err := a.CveChildren().All(ctx, tx)
+	check, err := a.Children().All(ctx, tx)
 	if err != nil {
 		t.Fatal(err)
 	}
@@ -411,18 +411,18 @@ func testCveToManyCveChildren(t *testing.T) {
 	}
 
 	slice := CveSlice{&a}
-	if err = a.L.LoadCveChildren(ctx, tx, false, (*[]*Cve)(&slice), nil); err != nil {
+	if err = a.L.LoadChildren(ctx, tx, false, (*[]*Cve)(&slice), nil); err != nil {
 		t.Fatal(err)
 	}
-	if got := len(a.R.CveChildren); got != 2 {
+	if got := len(a.R.Children); got != 2 {
 		t.Error("number of eager loaded records wrong, got:", got)
 	}
 
-	a.R.CveChildren = nil
-	if err = a.L.LoadCveChildren(ctx, tx, true, &a, nil); err != nil {
+	a.R.Children = nil
+	if err = a.L.LoadChildren(ctx, tx, true, &a, nil); err != nil {
 		t.Fatal(err)
 	}
-	if got := len(a.R.CveChildren); got != 2 {
+	if got := len(a.R.Children); got != 2 {
 		t.Error("number of eager loaded records wrong, got:", got)
 	}
 
@@ -431,7 +431,7 @@ func testCveToManyCveChildren(t *testing.T) {
 	}
 }
 
-func testCveToManyAddOpCveChildren(t *testing.T) {
+func testCveToManyAddOpChildren(t *testing.T) {
 	var err error
 
 	ctx := context.Background()
@@ -468,7 +468,7 @@ func testCveToManyAddOpCveChildren(t *testing.T) {
 	}
 
 	for i, x := range foreignersSplitByInsertion {
-		err = a.AddCveChildren(ctx, tx, i != 0, x...)
+		err = a.AddChildren(ctx, tx, i != 0, x...)
 		if err != nil {
 			t.Fatal(err)
 		}
@@ -490,14 +490,14 @@ func testCveToManyAddOpCveChildren(t *testing.T) {
 			t.Error("relationship was not added properly to the foreign slice")
 		}
 
-		if a.R.CveChildren[i*2] != first {
+		if a.R.Children[i*2] != first {
 			t.Error("relationship struct slice not set to correct value")
 		}
-		if a.R.CveChildren[i*2+1] != second {
+		if a.R.Children[i*2+1] != second {
 			t.Error("relationship struct slice not set to correct value")
 		}
 
-		count, err := a.CveChildren().Count(ctx, tx)
+		count, err := a.Children().Count(ctx, tx)
 		if err != nil {
 			t.Fatal(err)
 		}
```

**Comment by aarondl** [comment]
Rather than add a whole separate configuration option for this, doesn't it make sense to just add a fix to `strmangle` so this becomes a known singular?

**Comment by stephenafamo** [comment]
Closing this since the PR to `strmangle` is the preferred fix

**Pull request closed without merging**
