### PR TITLE
TableNames now honors config alias overrides

### LINKED ISSUE #813: models.TableNames does not match alias definitions
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.2.0

### What is your database and version (eg. Postgresql 10)
Postgresql 12

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
sqlboiler psql (I have the following in my sqlboiler.toml file)
```toml
[aliases.tables.ab_envs]
up_plural = "ABEnvs"
up_singular = "ABEnv"
down_plural = "abEnvs"
down_singular = "abEnv"
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)
```sql
CREATE TABLE IF NOT EXISTS ab_envs (id serial PRIMARY KEY, name varchar(25) NOT NULL UNIQUE);
```
### Further information. What did you do, what did you expect?
I ran sqlboiler, no errors, and everything except the models.TablesNames use the alias as defined.
models.TableNames contains AbEnvs instead of ABEnvs.  I would expect model.TableNames to be consistent with the alias definitions.

### PR DESCRIPTION
**Pull request by mgrubb**
Fixes #813

### CODE REVIEW

**Comment by aarondl** [comment]
You know I hadn't thought about it until just now. But this is a breaking change :( Meaning we can't add it since suddenly people's generated code will fail to compile if they just regenerate. Backwards compatibility is tough.

**Comment by mgrubb** [comment]
Would a command flag to switch this change on and keep the default behavior as it is be adequate to address backward compatibility?

**Comment by aarondl** [comment]
I'd rather just leave it until the next major version.

**Comment by aarondl** [comment]
The next major version has no release date and isn't really being "planned". We could consider flagging this if it's that important for users.

**Comment by stephenafamo** [comment]
Kindy reopen this PR to master, it was mistakenly closed when the dev branch was deleted.

**Pull request closed without merging**
