### PR TITLE
Feature/make enums own type

### PR DESCRIPTION
**Pull request by stephenafamo**
Continued from #834 , fixes indentation in `boil_types.go.tpl`

### CODE REVIEW

**Comment by tomscholz** [comment]
Awesome!

**Comment by aarondl** [comment]
Haha sorry @stephenafamo but this brings a whole-file inconsistency to the indentation that I asked to clean up. Can it go to tabs like the rest of the project's templates? :)

**Comment by stephenafamo** [comment]
@aarondl fixed the indentaion. Properly this time 😅

**Comment by aarondl** [comment]
Merging. Thanks for this!

**Pull request merged**
