### PR TITLE
fix: qm.Limit(0) should generate LIMIT 0

### PR DESCRIPTION
**Pull request by longngn**
Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

Fixes https://github.com/volatiletech/sqlboiler/issues/871

### CODE REVIEW

**Comment by aarondl** [comment]
This is PR'd against the wrong branch. See CONTRIBUTING.md.

**Comment by longngn** [comment]
> This is PR'd against the wrong branch. See CONTRIBUTING.md.

@aarondl I've fixed it

**Comment by aarondl** [comment]
Thanks @longngn

**Comment by PumpkinSeed** [comment]
Note: This is a breaking change. We updated from 4.5.0 to 4.13.0 and it's broke our existing code however the Changelog tells that it's only a [fix](https://github.com/volatiletech/sqlboiler/blob/v4.6.0/CHANGELOG.md). Something to keep in mind in this case.

**Pull request merged**
